name: ci
on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      # FIXME: there is no easy way to run integration tests for the ARM target
      # since the hosted runners are only x86_64.
      # While this removes some coverage, those tests are disabled for now.
      matrix:
        build:
          - linux
          - macos
          #- linux-arm
        include:
          - build: linux
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-11
            target: x86_64-apple-darwin
          #- build: linux-arm
            #os: ubuntu-20.04
            #target: arm-unknown-linux-gnueabihf
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target=${{ matrix.target }}

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
